import Head from "next/head";
import Navbar from "@/components/Navbar/Navbarapp";
import Hero from "@/components/Hero/Heroapp";
import NuevoConcepto from "@/components/NuevoConcepto/NuevoConceptoapp";
import ExpForza from "@/components/ExperienciaForza/ExperienciaForzaapp";
import NuestroEspacio from "@/components/NuestroEspacio/NuestroEspacioapp";
import Marco from "@/components/Marco/marcoapp";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main style={{ scrollBehavior: "smooth" }}>
        <Navbar></Navbar>
        <Hero></Hero>
        <NuevoConcepto></NuevoConcepto>
        {/* <Marco></Marco> */}
        <ExpForza></ExpForza>
        <NuestroEspacio></NuestroEspacio>
      </main>
    </>
  );
}
